import React from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Cog, ArrowLeft, Bot, MessageSquare, Share2, BarChart3, FileText, GraduationCap } from 'lucide-react';

const AIAutomation = () => {
  const features = [
    {
      title: 'AI Personal Assistant',
      description:
        'Automate reminders, meeting scheduling, task summaries, and internal communications — all through a smart, integrated assistant trained on your workflows.',
      icon: Bot,
    },
    {
      title: 'AI Chatbot for Website & WhatsApp',
      description:
        '24/7 conversational support for customers. Handles FAQs, lead qualification, support tickets, and even sends resources or schedules calls — in real-time, in multiple languages.',
      icon: MessageSquare,
    },
    {
      title: 'AI Social Media Manager',
      description:
        'Plan, write, design, and schedule content using AI. Generate smart captions, hashtags, and visuals while tracking engagement across platforms like LinkedIn, Instagram, and TikTok.',
      icon: Share2,
    },
    {
      title: 'Smart Analytics & Reporting',
      description:
        'Receive automated dashboards and performance summaries from your website, CRM, and social platforms — with actionable insights generated by AI.',
      icon: BarChart3,
    },
    {
      title: 'Contract & Proposal Generator',
      description:
        'No more manual document creation. Our AI builds service agreements, NDAs, and proposals instantly using pre-set templates — ready for e-signature.',
      icon: FileText,
    },
    {
      title: 'AI Knowledge Hub & Workflow Trainer',
      description:
        "Build an intelligent internal system that trains your team, answers their questions, and guides them through daily workflows. Whether it's onboarding new employees or explaining your company's internal processes, our AI-powered hub uses smart avatars, tutorials, and searchable guidance to keep your team aligned — without repetitive meetings.",
      icon: GraduationCap,
    },
  ];

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="min-h-screen pt-24 pb-16 px-4 bg-[#EBEBDF]"
    >
      <div className="max-w-7xl mx-auto">
        {/* Back Button */}
        <motion.div
          initial={{ x: -30, opacity: 0 }}
          animate={{ x: 0, opacity: 1 }}
          className="mb-8"
        >
          <Link
            to="/capability-building"
            className="inline-flex items-center text-[#080844]/80 hover:text-[#EA7946] transition-colors duration-200"
          >
            <ArrowLeft size={20} className="mr-2" />
            Back to Capability Building
          </Link>
        </motion.div>

        <div className="flex flex-col gap-12 items-start">
          {/* Content Section */}
          <motion.div
            initial={{ x: -50, opacity: 0 }}
            animate={{ x: 0, opacity: 1 }}
            transition={{ delay: 0.2 }}
            className="space-y-8"
          >
            <div className="space-y-6">
              <div className="w-16 h-16 rounded-full bg-[#EA7946] flex items-center justify-center">
                <Cog className="text-white" size={32} />
              </div>

              <h1 className="text-4xl md:text-5xl font-bold text-[#080844]">
                AI Automation System
              </h1>

              <div className="space-y-4">
                <p className="text-lg font-bold text-[#080844]">
                  Make your business work smarter — not harder.
                </p>

                <p className="text-[#080844] leading-relaxed">
                  At Zuccess, we design and implement intelligent AI systems that
                  handle the work you don't have time for. From automating internal
                  operations to enhancing your client experience, our AI-driven
                  tools are built to simplify, scale, and optimize your business
                  performance — all while keeping your brand voice intact.
                </p>

                <p className="text-[#080844] leading-relaxed">
                  Whether you're looking to reduce manual tasks, increase
                  responsiveness, or simply get more done with less effort, our
                  automation suite empowers your team to focus on what truly
                  matters.
                </p>
              </div>
            </div>

            {/* CTA Buttons */}
            <div className="flex flex-col sm:flex-row gap-4">
              <Link
                to="/contact"
                className="bg-[#EA7946] text-white px-8 py-4 rounded-lg hover:shadow-lg transition-all duration-300 transform hover:scale-105 text-center font-semibold"
              >
                Get Started
              </Link>
              <button className="bg-[#080844] text-white px-8 py-4 rounded-lg hover:bg-[#0a0a5c] transition-all duration-300 transform hover:scale-105 font-semibold">
                Request Demo
              </button>
            </div>
          </motion.div>

          {/* Features Section */}
          <motion.div
            initial={{ x: 50, opacity: 0 }}
            animate={{ x: 0, opacity: 1 }}
            transition={{ delay: 0.4 }}
            className="sticky top-24 w-full"
          >
            <div className="bg-white rounded-2xl p-6 border border-[#080844]/10 shadow-lg">
              <h3 className="text-2xl font-bold text-[#080844] mb-6">
                Key Features of Zuccess AI Automation
              </h3>

              <div className="space-y-6">
                {features.map((feature, index) => (
                  <motion.div
                    key={index}
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    transition={{ delay: index * 0.1 }}
                    className="flex items-start space-x-4 p-4 bg-[#EBEBDF] rounded-xl hover:bg-[#EA7946]/20 transition-all duration-300"
                  >
                    <div className="w-10 h-10 rounded-full bg-[#EA7946] flex items-center justify-center flex-shrink-0">
                      <feature.icon className="text-white" size={20} />
                    </div>
                    <div>
                      <h4 className="font-semibold text-[#080844] mb-2">
                        {feature.title}
                      </h4>
                      <p className="text-sm text-[#334155] leading-relaxed">
                        {feature.description}
                      </p>
                    </div>
                  </motion.div>
                ))}
              </div>
            </div>
          </motion.div>
        </div>
      </div>
    </motion.div>
  );
};

export default AIAutomation;
